services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: stefan_nemanja
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  react-app:
    build:
      context: ./Stefan_Nemanja_Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./Stefan_Nemanja_Front:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true