services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: stefan_nemanja
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


  react-app:
    build:
      context: ./stefan_nemanja_front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

